import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("http://10.31.2.177:8000/admin/login/?next=/admin/")
    page.get_by_text("Pule o conteúdo principal Administração do Django Alternar tema (tema atual:").click()
    page.locator("html").click()
    page.get_by_text("Pule o conteúdo principal Administração do Django Alternar tema (tema atual:").click()
    page.get_by_label("Usuário:").click()
    page.get_by_label("Senha:").click()
    page.get_by_label("Usuário:").click()
    page.get_by_label("Usuário:").click()
    page.get_by_label("Usuário:").press("CapsLock")
    page.get_by_label("Usuário:").fill("T")
    page.get_by_label("Usuário:").press("CapsLock")
    page.get_by_label("Usuário:").fill("Tester")
    page.get_by_label("Usuário:").click()
    page.get_by_label("Usuário:").press("ArrowLeft")
    page.get_by_label("Usuário:").press("ArrowLeft")
    page.get_by_label("Usuário:").press("ArrowLeft")
    page.get_by_label("Usuário:").press("ArrowLeft")
    page.get_by_label("Usuário:").press("ArrowLeft")
    page.get_by_label("Usuário:").fill("tester")
    page.get_by_label("Senha:").click()
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("escolafpftech1")
    page.get_by_role("button", name="Acessar").click()
    page.get_by_label("Senha:").click()
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("E")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("Escola")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("E")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("Escola")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("E")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("Esc@la")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("Esc@laFPF")
    page.get_by_label("Senha:").press("CapsLock")
    page.get_by_label("Senha:").fill("Esc@laFPFtech1")
    page.get_by_role("button", name="Acessar").click()
    page.locator("#content-start").click()
